title: <p align="center"> Hydrophilic Wonder </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">CV</a> |
  <a href="https://www.mathworks.com/matlabcentral/profile/authors/5027457/">MathWorks</a> |
  <a href="https://github.com/hydrophilic-wonder">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing a PhD in Biomedical Engineering at the University of Cape Town.
  <br><br>
  My research focuses on the application of supervised learning to predict 
  neurocognitive outcomes of children living with HIV from their neuroimaging measures.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
